cmake_minimum_required(VERSION 3.0.2)
project(pairs_softuav_simulation)

find_package(catkin REQUIRED COMPONENTS
  rospy
  std_msgs
  geometry_msgs
  nav_msgs
)

# Export the ROS-agnostic python library under src/pairs_softuav_sim
catkin_python_setup()

catkin_package()

catkin_install_python(PROGRAMS
  scripts/drone_sim_node.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)

install(DIRECTORY launch
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
